---
controller_inventories:
  - name: Filetree Inventory
    organization: Default
    description: created by Ansible Config as Code

controller_projects:
  - name: Ansible Project
    organization: Default
    scm_branch: development
    scm_clean: 'no'
    scm_delete_on_update: 'no'
    scm_type: git
    scm_update_on_launch: 'no'
    scm_url: https://github.com/r3dact3d/AnsibleProject.git

controller_templates:
  - name: Filetree Create
    organization: Default
    project: Ansible Project
    inventory: "Filetree Inventory"
    playbook: playbooks/filetree_create/filetree_create.yml
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials: []

  - name: Filetree Artifact
    organization: Default
    project: Ansible Project
    inventory: "Filetree Inventory"
    playbook: playbooks/filetree_create/filetree_artifact.yml
    scm_branch: ""
    forks: 0
    limit: "platform"
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials: []

controller_workflows:
  - name: "Filetree Workflow (WT)"
    description: !unsafe ''
    organization: "Default"
    simplified_workflow_nodes:
      - identifier: "Filetree Create"
        workflow_job_template: "Filetree Workflow (WT)"
        unified_job_template: "Filetree Create"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Filetree Artifact"
      - identifier: "Filetree Artifact"
        workflow_job_template: "Filetree Workflow (WT)"
        unified_job_template: "Filetree Artifact"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    limit: ""
    ask_limit_on_launch: false
    ask_inventory_on_launch: false
    webhook_service: ""
    extra_vars: ""
    labels: ""
    survey_enabled: false