---
- name: Blinker19 Kafka Events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        name: Kafka Event Source
        host: 192.168.1.177
        port: 9092
        topic: homeassistant1

  rules:
    - name: kafka
      condition: event. is defined
      action:
        debug:
          msg: "{{ event.body }}"
