---
- name: Blinker19 Kafka Events
  hosts: all
  sources:
    - ansible.eda.kafka:
        name: Kafka Event Source
        host: 192.168.1.177
        port: 9092
        topic: homeassistant1

  rules:
    - name: kafka
      condition: event.body.message != ""
      action:
        debug:
          msg: "{{ event.body.message }}"
