---
- name: Check Blinker19 LLM Services
  hosts: localhost
  sources:
    - ansible.eda.url_check:
      delay: 30
      verify_ssl: false
      urls:
        - https://0ri0n.blinker19.com

  rules:
    - name: Print event
      condition: event.url_check.status
      action:
        print_event:
          pretty: true

#        run_job_template:
#          name: Restart a container running on Proxmox VE
#          organization: Blinker19
#          job_args:
#            extra_vars:
#              IP_ADDRESS: 192.168.1.232