---
- name: Check Blinker19 Services and Debug URL Events
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        name: critical_services
        delay: 30 # How often to check in seconds
        verify_ssl: false
        urls:
          - http://192.168.1.180/admin # Pi-hole
          - https://192.168.1.232:8006 # Proxmox

  rules:
    - name: Critical Service DOWN - Notify and Restart
      condition: event.url_check.status == "down"
      actions:
        - debug:
            msg: "Placeholder for notification: Critical service DOWN: {{ event.url_check.url }}."

    - name: Critical Service Recovery Notification
      condition: event.url_check.status == "up" and event.previous_status == "down"
      action:
        print_event:
          msg: "CRITICAL SERVICE RECOVERED: {{ event.url_check.url }} is UP!"
          pretty: true
