---
- name: Blinker19 DNS Services
  hosts: localhost
  vars:
    check_status: "{{ INPUT_STATUS | default(down) }}"
  sources:
    - ansible.eda.url_check:
        name: internal_services
        delay: 300
        verify_ssl: false
        urls:
          - http://pihole-vip.pi.hole/admin
          - http://clearbox/admin
          - http://blackbox/admin
  rules:
    - name: Internal DNS Service "{{ check_status }}"
      condition: event.url_check.status == "{{ check_status }}"
      actions:
        - debug:
            msg: "Internal service {{ event.url_check.url }} is {{ check_status }}."
        - run_workflow_template:
            name: "URL Check Remediation"
            organization: "Blinker19"

