---
- name: Blinker19 LLM Services
  hosts: localhost
  vars:
    check_status: "{{ INPUT_STATUS | default(down) }}"
  sources:
    - ansible.eda.url_check:
        name: internal_services
        delay: 300
        verify_ssl: false
        urls:
          - http://ollama:11434
          - https://0ri0n.blinker19.com
           # Ollama/OpenWeb Ui
  rules:
    - name: Blinker19 LLM Service Status
      condition: event.url_check.status == "{{ check_status }}"
      actions:
        - debug:
            msg: "Internal service {{ event.url_check.url }} is {{ check_status }}."
        - run_workflow_template:
            name: "URL Check Remediation"
            organization: "Blinker19"
