---
- name: Blinker19 Internal Services
  hosts: localhost
  vars:
    check_status: "{{ INPUT_STATUS | default(down) }}"
  sources:
    - ansible.eda.url_check:
        name: critical_services
        delay: 30 # How often to check in seconds
        verify_ssl: false
        urls:
          - https://192.168.1.232:8006 # Proxmox

  rules:
    - name: Blinker19 Internal Service Status
      condition: event.url_check.status == "{{ check_status }}"
      actions:
        - debug:
            msg: "Internal service {{ event.url_check.url }} is {{ check_status }}."
        - run_workflow_template:
            name: "URL Check Remediation WT"
            organization: "Blinker19"
