---
- name: Check Blinker19 Home Assistant
  hosts: localhost
  sources:
    - ansible.eda.url_check:
      delay: 30
      verify_ssl: false
      urls:
        - http://192.168.1.87:8123/lovelace/0

  rules:
    - name: Print event
      condition: event.status
      action:
        print_event:
          pretty: true

#        run_job_template:
#          name: Restart a container running on Proxmox VE
#          organization: Blinker19
#          job_args:
#            extra_vars:
#              IP_ADDRESS: 192.168.1.232