---
- name: Check Blinker19 LAN Services
  hosts: localhost
  sources:
    - ansible.eda.url_check:
      urls:
        - http://192.168.1.180/admin
        - http://192.168.1.87:8123
      delay: 10
      verify_ssl: false

  rules:
    - name: Print event
      condition: event.status == "enabled"
      action:
        debug:

#        run_job_template:
#          name: Restart a container running on Proxmox VE
#          organization: Blinker19
#          job_args:
#            extra_vars:
#              IP_ADDRESS: 192.168.1.232