---
- name: Check Blinker19 Services and Debug URL Events
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        name: critical_services
        delay: 30 # How often to check in seconds
        verify_ssl: false
        urls:
          - http://192.168.1.180/admin
          - https://192.168.1.232:8006
    - ansible.eda.url_check:
        name: internal_services
        delay: 300
        verify_ssl: false
          - https://0ri0n.blinker19.com
          - http://192.168.1.87:8123/lovelace/0

  rules:
    - name: Critical Service DOWN - Notify and Restart
      condition: event.url_check.status == "down" and event.url_check.url in ["http://192.168.1.180/admin", "https://192.168.1.232:8006"]
      actions:
        - debug:
            msg: "Placeholder for notification: Critical service DOWN: {{ event.url_check.url }}."
        - run_job_template:
            name: "Restart Proxmox Container"
            organization: "Blinker19"
            job_args:
              extra_vars:
                IP_ADDRESS: "{{ '192.168.1.232' }}"

    - name: Recovery Notification
      condition: event.url_check.status == "up" and event.previous_status == "down"
      action:
        print_event:
          msg: "SERVICE RECOVERED: {{ event.url_check.url }} is UP!"
          pretty: true
