---
- name: Playbook to get info on Proxmox nodes
  hosts: localhost
  tasks:
    - name: Print the stat artifact
      ansible.builtin.debug:
        var: proxmox_nodes_artifact
    - name: Create new container with minimal options
      community.general.proxmox:
        node: {{ proxmox_nodes_artifact.proxmox_nodes[0].node }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') | default(omit) }}"
        api_host: "{{ lookup('env', 'PROXMOX_IP') }}"
        password:  "{{ host_password }}"
        hostname: "{{ ct_hostname }}"
        ostemplate: 'local:vztmpl/fedora-41-default_20241118_amd64.tar.xz'