---
- name: Restart a container running on Proxmox VE
  hosts: localhost
  tasks:
    - name: List existing nodes
      community.general.proxmox_node_info:
        api_host: "{{ IP_ADDRESS }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') | default(omit) }}"
        api_token_id: "{{ token_id | default(omit) }}"
        api_token_secret: "{{ token_secret | default(omit) }}"
      register: proxmox_nodes
      
    - name: Print proxmox_nodes stdout
      ansible.builtin.debug:
        var: proxmox_nodes

    - name: Export proxmox_nodes variable as artifact
      ansible.builtin.set_stats:
        data:
          proxmox_nodes_artifact: "{{ proxmox_nodes.stdout }}"