---
- name: Playbook to List all existing virtual machines on node
  hosts: localhost
  tasks:
    - name: Print the stat artifact
      ansible.builtin.debug:
        var: proxmox_nodes_artifact

    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: "{{ lookup('env', 'PROXMOX_IP') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') | default(omit) }}"
        api_token_id: "{{ token_id | default(omit) }}"
        api_token_secret: "{{ token_secret | default(omit) }}"
        node: "{{ proxmox_nodes_artifact.proxmox_nodes[0].node }}"
      register: proxmox_vms

    - name: Print the proxmox_vms variable
      ansible.builtin.debug:
        var: proxmox_vms

    - name: Export proxmox_vms variable as artifact
      ansible.builtin.set_stats:
        data:
          proxmox_vms_artifact: "{{ proxmox_vms }}"

