---
- name: Playbook to get info on Proxmox container
  hosts: localhost
  tasks:
    - name: Print the stat artifact
      ansible.builtin.debug:
        var: proxmox_new_container_artifact

    - name: Info on specific vm/container on node
      community.general.proxmox_vm_info:
        api_host: "{{ lookup('env', 'PROXMOX_IP') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') | default(omit) }}"
        api_token_id: "{{ token_id | default(omit) }}"
        api_token_secret: "{{ token_secret | default(omit) }}"
        node: "{{ proxmox_nodes_artifact.proxmox_nodes[0].node }}"
        vmid: "{{ proxmox_new_container_artifact.vmid }}"
      register: proxmox_container_info

    - name: Export new_container variable as artifact
      ansible.builtin.set_stats:
        data:
          proxmox_new_container_artifact: "{{ proxmox_container_info }}"