---
- name: Check Blinker19 Pi-hole DNS
  hosts: localhost
  gather_facts: true
  sources:
    - name: url_check
      ansible.eda.url_check:
        urls:
          - http://192.168.1.180/admin
        delay: 10
        verify_ssl: false
  rules:
    - name: Print event 
      condition: event.status == "enabled"
      action:
        debug: