---
- name: Ask LLM a Question
  hosts: localhost
  gather_facts: false
  collections:
    - redhat.ai 
  vars:
    OLLAMA_TOKEN: "{{ (lookup('env', 'MY_TOKEN')) | default(null) }}"
    OLLAMA_URL: "{{ (lookup('env', 'BASE_URL')) | default(http://1.2.3.4:8000) }}"
  tasks:
    - name: Ask model a question
      redhat.ai.completion:
        base_url: "{{ OLLAMA_URL }}"
        token: "{{ OLLAMA_TOKEN }}"
        prompt: "\n\n### Instructions:\nCapital of India?\n\n### Response:\n"
#        model_path: /var/home/ec2-user/.cache/instructlab/models/granite-8b-starter-v1
      delegate_to: localhost