---
- name: Ask LLM a Question
  hosts: localhost
  gather_facts: false
  collections:
    - redhat.ai 
  vars:
    OLLAMA_TOKEN: "{{ (lookup('env', 'MY_TOKEN')) }}"
    OLLAMA_URL: "http://192.168.1.100:11434"
    OLLAMA_MODEL: "/root/.ollama/models/manifests/registry.ollama.ai/library/granite3.1-moe/3b"
  tasks:
    - name: Print vars list OLLAMA_TOKEN OLLAMA_URL OLLAMA_MODEL
      ansible.builtin.debug:
        msg:
          - 'OLLAMA_TOKEN: {{ OLLAMA_TOKEN }}'
          - 'OLLAMA_URL: {{ OLLAMA_URL }}'
          - 'OLLAMA_MODEL: {{ OLLAMA_MODEL }}'

    - name: Ask model a question
      redhat.ai.completion:
        base_url: "{{ OLLAMA_URL }}"
        token: "{{ OLLAMA_TOKEN }}"
        model_path: "{{ OLLAMA_MODEL }}"
        prompt: "\n\n### Instructions:\nCapital of India?\n\n### Response:\n"
        validate_certs: false
#      delegate_to: localhost