---
- name: Interact with LLM for Home Assistant JSON Analysis
  hosts: localhost
  gather_facts: false
  vars:
    ollama_api_url: "{{ lookup('env', 'OLLAMA_API_URL') }}"
    ollama_api_token: "{{ lookup('env', 'OLLAMA_API_TOKEN') }}"
    ollama_api_model: 'granite3.1-moe:3b'


  tasks:
    - name: Set Home Assistant JSON as a fact
      ansible.builtin.set_fact:
        home_assistant_json_output: "{{ ansible_eda }}"

    - name: Prepare the prompt for the LLM
      ansible.builtin.set_fact:
        llm_prompt: |
          You are an AI assistant specialized in Home Assistant, Ansible, Python and JSON data.
          I have the following JSON output from Home Assistant:

          ```json
          {{ home_assistant_json_output | to_nice_json }}
          ```

          Please perform the following tasks:
          1. Explain what this JSON data represents in the context of Home Assistant.
          2. Use your expertise and experience to suggest how to use this information.
          3. Blow my mind


    - name: Display the prepared prompt (for debugging)
      ansible.builtin.debug:
        var: llm_prompt
      when: true

    - name: Call LLM API and Register Response
      ansible.builtin.uri:
        url: "{{ ollama_api_url }}/api/chat"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ ollama_api_token }}"
        body_format: json
        body: {
          "model": "{{ ollama_api_model }}",
          "stream": false,
          "messages": [
            {
              "role": "user",
              "content": "{{ llm_prompt }}"
            }
          ],
          "temperature": 0.1
        }
        status_code: 200
        return_content: true
        timeout: 60
      register: llm_api_response

    - name: Print the llm_api_response
      ansible.builtin.debug:
        var: llm_api_response
