---
- name: Send post request to openai API
  hosts: localhost
  vars:
    ollama_api_url: "{{ lookup('env', 'OLLAMA_API_URL') }}"
    ollama_api_token: "{{ lookup('env', 'OLLAMA_API_TOKEN') }}"
    ollama_api_model: 'granite3.1-moe:3b'

  tasks:
    - name: Send POST request using uri module
      ansible.builtin.uri:
        url: "{{ ollama_api_url }}/api/generate"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ ollama_api_token }}"
        body:
          prompt: "{{ ollama_prompt | default('What is the capital of the USA?') }}"
          model: "{{ ollama_api_model | default('granite3.1-moe:3b') }}"
          stream: false
          options:
            temperature: 0.2
            top_p: 0.9
            num_keep: 1
        body_format: json
        return_content: true
        status_code: 200
        timeout: 60
      register: ollama_response

    - name: Print the ollama_response variable
      ansible.builtin.debug:
        var: ollama_response
