---
- name: Send post request to openai API
  hosts: localhost
  vars:
    ollama_ip: 192.168.1.100
    ollama_port: 11434
    ollama_token: happy_token
    ollama_model: 'granite3.1-moe:3b'

  tasks:
    - name: Send POST request using uri module
      ansible.builtin.uri:
        url: "http://{{ ollama_ip }}:{{ ollama_port }}/v1/completions"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ ollama_token }}"
        body:
          prompt: "{{ ollama_prompt | default('What is the capital of the USA?') }}"
          max_tokens: "{{ max_tokens | default('50') }}"
          model: "{{ ollama_model | default('granite3.1-moe:3b') }}"
          temperature: "{{ input_temperature | default(0) }}"
          top_p: "{{ input_top_p | default(1) }}"
          n: "{{ input_n | default(1) }}"
        body_format: json
        return_content: true
        status_code: 200
        timeout: 60
      register: ollama_response
