---
- name: Copy filetree artifact playbook
  hosts: localhost
  tasks:
    - name: Print the artifact
      ansible.builtin.debug:
        var: filetree_output_stat

    - name: Print processed_file_data artifact variable
      ansible.builtin.debug:
        var: processed_file_data

    - name: Copy artifact to locally to platform
      ansible.builtin.copy:
        content: "{{ filetree_output_stat }}"
        dest: /tmp/filetree_output_stat.yml