---
- name: Copy filetree artifact playbook
  hosts: all
  tasks:
    - name: Print the artifact
      ansible.builtin.debug:
        var: filetree_output_stat

    - name: Print processed_file_data artifact variable
      ansible.builtin.debug:
        var: processed_file_data

    - name: Check if file /tmp/filetree_output_stat.yml exists
      register: file_data
      ansible.builtin.stat:
        path: /tmp/filetree_output_stat.yml

    - name: Set stat from registered file_data
      when: file_data.stat.exists
      ansible.builtin.set_fact:
        filetree_output_orig: {{ lookup('file', '/etc/filetree_output_stat') }}"

    - name: Backup the previous artifact
      when: file_data.stat.exists
      ansible.builtin.copy:
        src: /tmp/filetree_output_stat.yml
        dest: /tmp/filetree_output_stat.yml.bak

    - name: Copy artifact locally to platform
      ansible.builtin.copy:
        content: "{{ filetree_output_stat }}"
        dest: /tmp/filetree_output_stat.yml

