---
- name: Copy filetree artifact playbook
  hosts: all
  tasks:
    - name: Print the artifact
      ansible.builtin.debug:
        var: filetree_output_stat

    - name: Print processed_file_data artifact variable
      ansible.builtin.debug:
        var: processed_file_data

    - name: Check if file /tmp/filetree_output_stat.yml exists
      register: file_data
      ansible.builtin.stat:
        path: /tmp/filetree_output_stat.yml

    - name: Slurp file from target host
      when: file_data.stat.exists
      register: slurp_file_data
      ansible.builtin.slurp:
        src: /tmp/filetree_output_stat.yml

    - name: Set stat
      when: file_data.stat.exists
      ansible.builtin.set_stats:
        data:
          filetree_output_orig: "{{ slurp_file_data.content | b64decode | from_yaml }}"

    - name: Backup the previous artifact
      when: file_data.stat.exists
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/filetree_output_stat.yml
        dest: /tmp/filetree_output_stat.yml.bak

    - name: Copy artifact locally to platform
      ansible.builtin.copy:
        content: "{{ filetree_output_stat }}"
        dest: /tmp/filetree_output_stat.yml

