---
- name: Create Inventory and Targets
  hosts: localhost
  gather_facts: no
  vars:
    target_list: targets.txt
    inventory_file: inventory
  tasks:
    - name: Write the inventory file
      ansible.builtin.template:
        src: inventory.j2
        dest: "{{ inventory_file }}"
