---
- name: Create Inventory and Targets
  hosts: localhost
  gather_facts: false
  vars:
    target_list: targets.txt
    target_inventory: inventory
  tasks:
    - name: Write the inventory file
      ansible.builtin.template:
        mode: '0644'
        src: inventory.j2
        dest: "{{ target_inventory }}"
