---
- name: Playbook to authenticate to one platform and export the resources
  hosts: localhost
  vars:
    aap_username: "{{ (lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ (lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ (lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ (lookup('env', 'CONTROLLER_VERIFY_SSL')) | default(false) }}"
    controller_validate_certs: false
    controller_oauthtoken: "{{ (lookup('env', 'CONTROLLER_OAUTH_TOKEN')) }}"
    flatten_output: True

  pre_tasks:
    - name: "Setup authentication (block)"
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always

  roles:
    - infra.aap_configuration_extended.filetree_create

  post_tasks:

    - name: Get matching files
      ansible.builtin.find:
        path: "/tmp/filetree_output"
      register: matched_files

    - name: Print matched_files variable
      ansible.builtin.debug:
        var: matched_files

    - name: Set fact from matched files
      ansible.builtin.set_fact:
        filetree_output_fact: "{{ matched_files.files | map(attribute='path') }}"

    - name: Print filetree_output_fact var 
      ansible.builtin.debug:
        var: filetree_output_fact

    - name: Slurp all YAML files
      ansible.builtin.slurp:
        src: "{{ item }}" # 'item' will be each file path from the loop
      loop: "{{ filetree_output_fact }}"
      register: slurped_files_results
      loop_control:
        label: "{{ item }}" 

    - name: Print slurped_files_results var
      ansible.builtin.debug:
        var: slurped_files_results
        verbosity: 2

    - name: Export filetree output as artifact
      ansible.builtin.set_stats:
        data:
          filetree_output_stat: "{{ matched_files.files | map(attribute='path') | list }}"
    
    - name: Print filetree_output_stat var 
      ansible.builtin.debug:
        var: filetree_output_stat

    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_hostname }}{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined

...