---
- name: Get and Read Variable between JT in a WF
  hosts: localhost
  connection: local
  gather_facts: false
   
  tasks:
    - name: print variable with msg
      debug:
        msg: "I don't know whats going on {{ new_variable }}"
        
    - name: print variable with var
      debug:
        var: new_variable