---
- name: Restart a container running on Proxmox VE
  hosts: localhost
  connection: local
  tasks:
    - name: Restart a container
      community.general.proxmox:
        vmid: 103
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        state: restarted