name: 'Ansible Dev Image Builder'
on:
  push:
    branches:
      - 'development'
    paths:
      - 'ee_builder.yml'
  workflow_dispatch:

jobs:
  Ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Run ansible playbook
        run: |
          ansible-galaxy collection install -r collections/requirements.yml
          ansible-playbook
            
